### ISSUE TITLE
Norme error

### ISSUE THREAD

**Issue by 42lan** [4slan/get_next_line#1]
function **get_next_line** has 28 lines

**Comment by 4slan** [comment]
I have divided **get_next_line()** creating a new function **get_line()** which deals with
1. search position (index) of \n
2. creating a new string from index **0** until **nl** and putting it in line
3. modifying static variable **save**

Thanks to @abaisango and @belkaqd

**Comment by 42lan** [comment]
I have divided get_next_line() creating a new function get_line() which deals with

search position (index) of \n
creating a new string from index 0 until nl and putting it in line
modifying static variable save
Thanks to @abaisango and @belkaqd
